on: [push]
env: 
  NAMESPACE: staging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemodefender.azurecr.io
        username: ${{ secrets.acr_acrdemodefender_username }}
        password: ${{ secrets.acr_acrdemodefender_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/mysql" -f  "src/mysql/Dockerfile" -t acrdemodefender.azurecr.io/aksdemodefender:${{ github.sha }}-mysql --label dockerfile-path=src/mysql/Dockerfile
    
    - uses: Azure/container-scan@v0 
      name: Scan image for vulnerabilities
      id: container-scan
      continue-on-error: true
      with:
        image-name: acrdemodefender.azurecr.io/aksdemodefender:${{ github.sha }}-mysql 

    - name: Push image to ACR
      id: push-image
      run: |
        docker push acrdemodefender.azurecr.io/aksdemodefender:${{ github.sha }}-mysql

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }} 
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemodefender_kubeconfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ${{ env.NAMESPACE  }} | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ${{ env.NAMESPACE  }}`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: acrdemodefender.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemodefender_username }}
        container-registry-password: ${{ secrets.acr_acrdemodefender_password }}
        secret-name: aksdemodefendockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          manifests/mysqlsecret.yaml
          manifests/mysqlset.yaml
          manifests/mysqlservice.yaml
        images: |
          acrdemodefender.azurecr.io/aksdemodefender:${{ github.sha }}-mysql
        imagepullsecrets: |
          aksdemodefendockerauth
